### ISSUE TITLE
cannot find package "github.com/robfig/cron/v3"

### ISSUE THREAD

**Issue by naughtydevelopment** [bamzi/jobrunner#14]
When we want to build our code after `go get -v `we get this following error. There is no package such as "github.com/robfig/cron/v3"

`github.com/robfig/cron (download)
package github.com/robfig/cron/v3: cannot find package "github.com/robfig/cron/v3" in any of:
	/usr/local/go/src/github.com/robfig/cron/v3 (from $GOROOT)
	/go/src/github.com/robfig/cron/v3 (from $GOPATH)`

**Comment by bamzi** [comment]
Did you try `go get -u github.com/robfig/cron`

V3 is in a separate branch

**Comment by naughtydevelopment** [comment]
Thanks for your immediate reply @bamzi. I tried to update/delete package before but I got same error. `go get` couldn't find the `cron/v3`. Also I use the commend `go get -v` in fresh docker container for build my app. So even that time I got same error. Because of that I think this is not package update issue.

**Comment by naughtydevelopment** [comment]
I migrated the project golang's new package version approach `modules`. But I didn't test and also I don't now how can push my changing branch.

**Comment by bamzi** [comment]
I should’ve checked before accepting the pull requested

I’ve fixed it in the latest 

You need to `go get gopkg.in/robfig/cron.v3`

**Comment by naughtydevelopment** [comment]
It worked when you changed the package source. Our application has been successfully built. Thank you so much @bamzi.
