### ISSUE TITLE
github.com/robfig/cron/v3: cannot find package 

### ISSUE THREAD

**Issue by JasminaDzevlan** [bamzi/jobrunner#23]
While installing bamzi/jobrunner with glide I get this error :
Error scanning github.com/robfig/cron/v3: cannot find package "." in:
 When I went to search package "github.com/robfig/cron/v3" I got 404 error.
Then I found that I need to replace it with this package "gopkg.in/robfig/cron.v3" by hand.

I need to be able to install this plugin just with glide. Will you fix this issue ??  

Thank you in advance for your replay.

**Comment by bamzi** [comment]
similar to #20 
First -> go get -u github.com/robfig/cron so that your base lib is updated to latest and then go get github.com/robfig/cron/v3@v3.0.0 to get the latest tags
