### ISSUE TITLE
Getting error on dep ensure -add

### ISSUE THREAD

**Issue by psych01905** [bamzi/jobrunner#28]
Hi I am getting error when I am trying to the add the dependency. 
Error is

Fetching sources...

ensure Solve(): No versions of github.com/robfig/cron met constraints:
	v3.0.1: Could not introduce github.com/robfig/cron@v3.0.1, as its subpackage github.com/robfig/cron/v3 is missing. (Package is required by github.com/bamzi/jobrunner@master.)
	v3.0.0: Could not introduce github.com/robfig/cron@v3.0.0, as its subpackage github.com/robfig/cron/v3 is missing. (Package is required by github.com/bamzi/jobrunner@master.)
	v1.2.0: Could not introduce github.com/robfig/cron@v1.2.0, as its subpackage github.com/robfig/cron/v3 is missing. (Package is required by github.com/bamzi/jobrunner@master.)
	v1.1.0: Could not introduce github.com/robfig/cron@v1.1.0, as its subpackage github.com/robfig/cron/v3 is missing. (Package is required by github.com/bamzi/jobrunner@master.)
	v1.0.0: Could not introduce github.com/robfig/cron@v1.0.0, as its subpackage github.com/robfig/cron/v3 is missing. (Package is required by github.com/bamzi/jobrunner@master.)
	v3.0.0-rc1: Could not introduce github.com/robfig/cron@v3.0.0-rc1, as its subpackage github.com/robfig/cron/v3 is missing. (Package is required by github.com/bamzi/jobrunner@master.)
	master: Could not introduce github.com/robfig/cron@master, as its subpackage github.com/robfig/cron/v3 is missing. (Package is required by github.com/bamzi/jobrunner@master.)
	v1: Could not introduce github.com/robfig/cron@v1, as its subpackage github.com/robfig/cron/v3 is missing. (Package is required by github.com/bamzi/jobrunner@master.)
	v2: Could not introduce github.com/robfig/cron@v2, as its subpackage github.com/robfig/cron/v3 is missing. (Package is required by github.com/bamzi/jobrunner@master.)
	v3: Could not introduce github.com/robfig/cron@v3, as its subpackage github.com/robfig/cron/v3 is missing. (Package is required by github.com/bamzi/jobrunner@master.)
	v3-dev: Could not introduce github.com/robfig/cron@v3-dev, as its subpackage github.com/robfig/cron/v3 is missing. (Package is required by github.com/bamzi/jobrunner@master.)

**Comment by bamzi** [comment]
similar to #20 & #23
First -> go get -u github.com/robfig/cron so that your base lib is updated to latest and then go get github.com/robfig/cron/v3@v3.0.0 to get the latest tags
